/**
 * TypeScript declarations for the Emscripten-compiled inventory Wasm module.
 * These types mirror the C++ classes exposed via Embind.
 */

export interface WasmProduct {
  getID(): string;
  getName(): string;
  getPrice(): number;
  getQuantity(): number;
  getValue(): number;
  delete(): void; // Embind pointers must be freed
}

export interface WasmInventory {
  // Core operations
  addProduct(id: string, name: string, price: number, qty: number): boolean;
  deleteProduct(id: string): boolean;
  purchaseStock(id: string, qty: number): number;  // returns new qty, -1 not found
  sellStock(id: string, qty: number): number;       // returns new qty, -1 not found, -2 insufficient
  updateProduct(id: string, name: string, price: number, qty: number): boolean;

  // Queries
  getProductCount(): number;
  getProductAt(index: number): WasmProduct;
  getTotalValue(): number;
  getLowStockCount(threshold: number): number;
  isLowStock(id: string, threshold: number): boolean;
  productExists(id: string): boolean;
  validateSell(id: string, qty: number): number; // 0=ok, 1=not found, 2=insufficient
  getAvailableQty(id: string): number;

  // Bulk operations
  clear(): void;
  loadProduct(id: string, name: string, price: number, qty: number): void;

  delete(): void; // Free Embind pointer
}

export interface InventoryModule {
  Product: {
    new(): WasmProduct;
    new(id: string, name: string, price: number, qty: number): WasmProduct;
  };
  Inventory: {
    new(): WasmInventory;
  };
}

/**
 * Factory function generated by Emscripten with MODULARIZE=1.
 * Returns a promise that resolves to the fully-initialized module.
 */
declare function createInventoryModule(): Promise<InventoryModule>;
export default createInventoryModule;
